name: Vercel Env (guard + manual sync)

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      sync:
        description: 'Sync GitHub Secrets → Vercel env (true/false)'
        required: false
        default: 'false'

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i -g vercel@latest
      - name: Link project
        run: vercel link --project $VERCEL_PROJECT_ID --org $VERCEL_ORG_ID --token $VERCEL_TOKEN
      - name: Fail if APPS_SCRIPT_URL is not exec URL
        run: |
          if ! echo "${{ secrets.APPS_SCRIPT_URL }}" | grep -Eq "/macros/s/.+/exec$"; then
            echo "::error ::GitHub Secret APPS_SCRIPT_URL должен быть URL веб-приложения (…/macros/s/.../exec)"; exit 1; fi
      - name: Show current Vercel env (prod)
        run: vercel env ls production --token $VERCEL_TOKEN || true
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

  sync:
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.sync == 'true' }}
    needs: guard
    runs-on: ubuntu-latest
    steps:
      - run: npm i -g vercel@latest
      - name: Link project
        run: vercel link --project $VERCEL_PROJECT_ID --org $VERCEL_ORG_ID --token $VERCEL_TOKEN
      - name: Push env to Vercel (production & preview)
        run: |
          set -e
          for ENV in production preview; do
            printf "%s" "${{ secrets.CFG_KEY }}"         | vercel env add CFG_KEY $ENV --yes --token $VERCEL_TOKEN
            printf "%s" "${{ secrets.APPS_SCRIPT_URL }}" | vercel env add APPS_SCRIPT_URL $ENV --yes --token $VERCEL_TOKEN
            printf "%s" "${{ secrets.ORIGIN }}"          | vercel env add ORIGIN $ENV --yes --token $VERCEL_TOKEN
            printf "%s" "${{ secrets.ORIGIN_PREVIEW }}"  | vercel env add ORIGIN_PREVIEW $ENV --yes --token $VERCEL_TOKEN
          done
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
