name: Vercel Env (Production only)

on:
  workflow_dispatch: {}     # запускаем вручную; никаких автозапусков

jobs:
  sync-env:
    runs-on: ubuntu-latest
    timeout-minutes: 7

    env:
      VERCEL_TOKEN:        ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID:       ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_NAME: ${{ secrets.VERCEL_PROJECT_NAME }}
      VERCEL_PROJECT_ID:   ${{ secrets.VERCEL_PROJECT_ID }}
      CFG_KEY:             ${{ secrets.CFG_KEY }}
      APPS_SCRIPT_URL:     ${{ secrets.APPS_SCRIPT_URL }}
      ORIGIN:              ${{ secrets.ORIGIN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sanity check of required secrets
        shell: bash
        run: |
          set -e
          [ -n "$VERCEL_TOKEN" ]        || { echo "Missing VERCEL_TOKEN"        >&2; exit 1; }
          [ -n "$VERCEL_ORG_ID" ]       || { echo "Missing VERCEL_ORG_ID"       >&2; exit 1; }
          [ -n "$CFG_KEY" ]             || { echo "Missing CFG_KEY"             >&2; exit 1; }
          [ -n "$APPS_SCRIPT_URL" ]     || { echo "Missing APPS_SCRIPT_URL"     >&2; exit 1; }
          if [ -z "$VERCEL_PROJECT_NAME" ] && [ -z "$VERCEL_PROJECT_ID" ]; then
            echo "Provide either VERCEL_PROJECT_NAME or VERCEL_PROJECT_ID" >&2; exit 1;
          fi

      - name: Install vercel CLI & python3
        run: |
          npm i -g vercel@latest
          sudo apt-get update -y
          sudo apt-get install -y python3

      - name: Resolve project flag (prefer NAME, fallback to ID)
        id: proj
        shell: bash
        run: |
          if [ -n "$VERCEL_PROJECT_NAME" ]; then
            echo "flag=--project \"$VERCEL_PROJECT_NAME\"" >> $GITHUB_OUTPUT
          else
            echo "flag=--project \"$VERCEL_PROJECT_ID\""   >> $GITHUB_OUTPUT
          fi

      # ---------- PRODUCTION ----------
      - name: Remove existing envs (production)
        shell: bash
        run: |
          set -e
          for K in CFG_KEY APPS_SCRIPT_URL ORIGIN; do
            vercel env rm "$K" production --yes \
              --token "$VERCEL_TOKEN" --scope "$VERCEL_ORG_ID" ${{ steps.proj.outputs.flag }} || true
          done

      - name: Add envs (production)
        shell: bash
        run: |
          set -e
          # обязательные
          printf '%s' "$CFG_KEY"         | vercel env add CFG_KEY         production --force --token "$VERCEL_TOKEN" --scope "$VERCEL_ORG_ID" ${{ steps.proj.outputs.flag }}
          printf '%s' "$APPS_SCRIPT_URL" | vercel env add APPS_SCRIPT_URL production --force --token "$VERCEL_TOKEN" --scope "$VERCEL_ORG_ID" ${{ steps.proj.outputs.flag }}
          # опциональный
          if [ -n "$ORIGIN" ]; then
            printf '%s' "$ORIGIN"        | vercel env add ORIGIN          production --force --token "$VERCEL_TOKEN" --scope "$VERCEL_ORG_ID" ${{ steps.proj.outputs.flag }}
          fi

      - name: Print key_id (diagnostic only)
        shell: bash
        run: |
          KEY_ID=$(python3 - <<'PY'
import os, hashlib
print(hashlib.sha256(os.environ.get('CFG_KEY','').encode()).hexdigest()[:12])
PY
)
          echo "key_id=${KEY_ID}"
